TIMEOUT=5

${WALLPAPER_PATH}=boot():/boot/logo.png
wallpaper: ${WALLPAPER_PATH}
wallpaper_style: centered
backdrop: 100000

/TermuOS
    protocol: limine
    kernel_path: boot():/boot/kernel.elf
    module_path: boot():/boot/icons/about.rgba
    module_path: boot():/boot/bin/echo.tsys
    module_path: boot():/boot/bin/uname.tsys
    module_path: boot():/boot/bin/cat.tsys
    module_path: boot():/boot/bin/edit.tsys
    module_path: boot():/boot/bin/lsdrv.tsys
    module_path: boot():/boot/bin/help.tsys
    module_path: boot():/boot/bin/luna.tsys
